word_embeddings:
  # Two types of word embedding algorithm (word2vec and glove) are supported.
  # Just set the default to empty string to disable the word embeddings
  default: word2vec
  word2vec:
    path: ../../data/input/word_embeddings/GoogleNews-vectors-negative300.bin
    dimension: 300
    binary: True
  glove:
    path: ../../data/glove.6B.100d.txt
    dimension: 100
    length: 400000

data_processing:
  current_data: id_ClassII_20200222_all.txt
  # clean
  row_split: "|-|"
  column_split: "||"
  # path
  stop_word_path: ../data/id_all_text/labels/stopwords-id.txt
  label_path: ../data/id_all_text/labels/model_to_category.csv
  ori_path: ../data/id_all_text/ori
  sys_label_path: ../data/id_all_text/labels/labelList_classII.txt
  labels_other: 34
  # sample
  sample_seed: 10

datasets:
  # Support currently 3 datasets: mrpolarity, 20newsgroup and localdata
  default: localdata
  mrpolarity:
    random_state: 42
    positive_data_file:
      path: "data/rt-polaritydata/rt-polarity.pos"
      info: "Data source for the positive data"
    negative_data_file:
      path: "data/rt-polaritydata/rt-polarity.neg"
      info: "Data source for the negative data"
  20newsgroup:
    # The dataset includes following 20 newsgroups:
    # alt.atheism, comp.windows.x, rec.sport.hockey, soc.religion.christian
    # comp.graphics, misc.forsale, sci.crypt, talk.politics.guns
    # comp.os.ms-windows.misc, rec.autos, sci.electronics, talk.politics.mideast
    # comp.sys.ibm.pc.hardware, rec.motorcycles, sci.med, talk.politics.misc
    # comp.sys.mac.hardware, rec.sport.baseball, sci.space, talk.religion.misc
    categories:
      - alt.atheism
      - comp.graphics
      - sci.med
      - soc.religion.christian
    shuffle: True
    random_state: 42
  localdata:
    # Load text files with categories as subfolder names.
    # Individual samples are assumed to be files stored
    # a two levels folder structure such as the following:
    # container_folder/
    #   category_1_folder/
    #     file_1.txt file_2.txt ... file_42.txt
    #   category_2_folder/
    #     file_43.txt file_44.txt ...
    #
    # As an example, a SentenceCorpus dataset from
    # https://archive.ics.uci.edu/ml/datasets/Sentence+Classification
    # has been used. The dataset includes following 3 domains:
    # arxiv, jdm and plos
    container_path: ./data/id_data_train
    test_path: ./data/id_data_test
    categories:
      - BodyCare
      - Fashion
      - make_up
      - skin_care
    shuffle: True
    random_state: 42

